# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://anhdao21.github.io/'
baseurl:             'study_journal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Anh Dao
  url:               [Twitter TBD]
  email:             adao0@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
